allprojects {
    repositories {
        google()
        mavenCentral()
        // maven { url uri('file:///Users/Manster/.m2/repository') }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
